### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by modulovalue** [modulovalue/flutter_raytracing#2]
I'd like for this project to work across all platforms without platform-dependent code. Any help with performance optimization that adheres to that constraint is appreciated.

**Comment by sachaarbonel** [comment]
For performance optimizations you could use [SIMD](http://dartdoc.takyam.com/articles/simd/) it is specially efficient on matrix operations

**Comment by sachaarbonel** [comment]
A simple step towards this would be to replace or extends some of the models of this package with the ones from the vector package. A non exhaustive list :
- [Ray](https://github.com/google/vector_math.dart/blob/b145d38080b2c9ecf1b77d91e2d28674a425518f/lib/src/vector_math/ray.dart) 
- [Colors](https://github.com/google/vector_math.dart/blob/1de61698353c439591730dd2c44420678575c9f2/lib/src/vector_math/colors.dart)

**Comment by modulovalue** [comment]
> For performance optimizations you could use SIMD it is specially efficient on matrix operations

Oh wow, I didn't know that Dart supported SIMD like that.
I had to switch to vector_math_64 because the single-precision version was causing artifacts. I see that SIMD operations are only supported on single-precision Float32x4 types, therefore, I believe that they might not be able to help here. (I'm not completely sure if I'm correct)

> Ray, Colors

The original RGB class uses a (1 - a) alpha value and one should be careful when exchanging the RGB class with Colors to not introduce subtle bugs.
